name: "Run tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-18.04', 'ubuntu-20.04', 'macos-10.15', 'macos-11' ]
        python: [ '2.7', '3.7', '3.8', '3.9', '3.10' ]
    name: Python ${{ matrix.python }} (${{ matrix.os }})
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Set up caching for pip (Linux)
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up caching for pip (macOS)
        uses: actions/cache@v3
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install core requirements
        run: pip install -r requirements.txt

      - name: Install Python 2.7 test requirements
        if: ${{ matrix.python == '2.7' }}
        run: pip install -r test_requirements_python27.txt

      - name: Install Python 3 test requirements
        if: ${{ matrix.python != '2.7' }}
        run: pip install -r test_requirements.txt

      - name: Run unit tests
        run: python -m unittest discover

      - name: Check setup.py metadata
        run: python setup.py check --metadata --strict

      - name: Run notebook tests
        run: |
          python ipynb_runner.py -v -s examples/example.ipynb
          python ipynb_runner.py -v -s examples/example_outputs.ipynb
          # Removed in https://github.com/rossant/ipycache/commit/632b7732622239cf363e3606f694735818ec6cc6
          # when this was using Travis CI; need to look into whether this needs to be re-enabled or removed.
          # python ipynb_runner.py -v -s examples/capture_output.ipynb
